- name: install packages (remi)
  yum:
    name={{ item }}
    state=latest
    enablerepo=remi
  with_items: "{{ REMI_PACKAGES }}"

- name: install packages
  yum:
    name={{ item }}
    state=latest
  with_items: "{{ PACKAGES }}"
