- name: Install MediaWiki skins

  hosts: vms

  roles:
    - install_skins

  environment: "{{ PROXY_ENV | default({}) }}"

  vars:

    SKINS:

      - name: "foreground"
        url: https://github.com/thingles/foreground.git
        version: master
